name: 'guard-action'
description: 'Guard ShiftLeft'
author: grolston
inputs:
  data_directory:
    description: 'directory within git repo to scan cloudformation templates'
    required: true
  rule_set:
    description: 'scanner used to run security test. Options are a lot, please read documentation.'
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield
  color: orange