name: 'ShiftLeft'
description: 'Guard ShiftLeft'
author: grolston
inputs:
  data_directory:
    description: 'directory within git repo to scan cloudformation templates'
    required: true
  rule_set:
    description: 'scanner used to run security test. Options are "FedRAMP-Low", "FedRAMP-Moderate", "NIST800-53Rev4", "NIST800-53Rev4", "PCI-DSS-3-2-1"'
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield
  color: orange